global_costmap:
# The "robot_base_link" parameter defines the coordinate frame the
# costmap should reference for the base of the robot.
    robot_base_frame: base_link

# The "update_frequency" parameter determines the frequency, in Hz, at
# which the costmap will run its update loop.
    update_frequency: 3.0

# The "publish_frequency" parameter determines the rate, in Hz, at
# which the costmap will publish visualization information.
    publish_frequency: 0.5

# The "static_map" parameter determines whether or not the costmap
# should initialize itself based on a map served by the map_server. If
# you aren't using an existing map or map server, set the static_map
# parameter to false.

# The "global_frame" parameter defines what coordinate frame the
# costmap should run in, in this case, we'll choose the /map frame.
    # global_frame: /map
    # static_map: true
    # rolling_window: false

    global_frame: /map
    static_map: true
    rolling_window: false

# The "width," "height," and "resolution" parameters set the width
# (meters), height (meters), and resoltion (meters/cell) of the
# costmap. Note that its fine for the resolution of this grid to be
# different than the resolution of your static map, but most of the
# time we tend to set them equally.
    #width: 6.0
    #height: 6.0
    #resolution: 0.1

# Other

    lethal_cost_threshold: 100
