#image: ../maps/map_1.3.C12_2014-12_stage.bmp
image: ../maps/map_1.3.C12_2014-12_clean.pgm

resolution: 0.050000

# This values point to the origin of coordinates. That is:
# from the "world" file, floorplan -> size [ length width height ]
#origin: [-4.375, -6.88, 0.00]
origin: [-3.475, -7.95, 0.00]

negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
